### PR TITLE
Move kotlin over to a testRuntime dependency

### PR DESCRIPTION
**Pull request by tdaffin**
Alright, one last thing -- an update to the README, as I've found in practice that kotlin is only needed as a testRuntime dependency in the user's mod.

Also, a quick question -- do you want to do an official 0.0.3 release?  I'd like to try adding this to the cyclops maven repo now, and it would be nice to have an offical jar built by the author to put there.

### CODE REVIEW

**Comment by jjtParadox** [comment]
A 0.0.3 release would be great! Unfortunately I'm not experienced with publishing to maven repos or similar (I haven't quite figured out how to digitally sign a jar just yet), but I can make a build for you to use!

**Comment by jjtParadox** [comment]
Released! https://github.com/jjtParadox/Barometer/releases/tag/v0.0.3-1.12

**Comment by tdaffin** [comment]
Awesome, thanks!  I don't know how to publish to maven either -- though I think you need a login to do it and so forth.  I've also never digitally signed a jar, but I think that @rubensworks has...  I'd be happy to try to figure this out too, so any hints or tips from @rubensworks would help :smile:

**Comment by rubensworks** [comment]
Up until recently, I used [Bintray](https://bintray.com/) for hosting artifacts. It's free, and easy to use. But due to the high number of jars I had to publish, I now use [oss.jfrog.org](https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org#DeployingSnapshotstooss.jfrog.org-ReleasingtoBintray) (also free), which would probably not be needed in this case.

If you want, I could look into setting up CI for this project and auto-publishing builds and releases (or at least help). This could be either in a separate Bintray organization, or the Cyclops oss.jfrog.org namespace, whatever you want :-)

In any case, feel free to reuse any of the Cyclops CI and release scripts.

**Comment by jjtParadox** [comment]
For now I'll just do a manual upload until releases become more frequent (and once I figure out the way I want to handle publishing scripts). v0.0.3 is now available over at https://bintray.com/jjtparadox/MC/Barometer :smiley:

**Pull request merged**
